### ISSUE TITLE
Use of Express Request object with Fastify 

### ISSUE THREAD

**Issue by mkgn** [chanphiromsok/Fastify-Upload#2]
To my understanding NestJs suggests not to use Express related Response/Request objects when using FastifyAdapter. But in your case you are using Express Request in FileMapper and also Express.Multer. Is this by mistake or is this ok to do?

**Comment by chanphiromsok** [comment]
yes it is ok to do so because fastify-multer is use multer from express so it is ok to use like this.
please take a look at his library instead https://www.npmjs.com/package/fastify-file-interceptor
